# Generated by Django 3.1.4 on 2021-02-24 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blogphoto',
            field=models.ImageField(blank=True, null=True, upload_to='post/image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Registeruser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('aboutpro', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('aboutprofile', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('photo', models.ImageField(default='profile/image/icon.jpg', null=True, upload_to='profile/image')),
                ('coverphoto', models.ImageField(default='profile/image/home-bg.jpg', null=True, upload_to='profile/image')),
                ('timeStamp1', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.registeruser'),
        ),
    ]
